server:
  port: ${TEST_SORT_PORT:8080}

spring:
  application:
    name: "TEST-SERVICE"

  output.ansi.enabled: ALWAYS


# swagger
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

